// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rabzhwhknlraygrrdkja.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhYnpod2hrbmxyYXlncnJka2phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NzkxNDYsImV4cCI6MjA4NzM1NTE0Nn0.MZrDU5fp959c3sWjCLN785OrYYrEX7hk3AnTJ0ePwBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});